added function and bdd for delete wishlist
CSCI-GA-2820-FA23-003/wishlists pull request #107
Opened 2023-11-30 01:51 UTC by raymondlu8547

added function and bdd for delete wishlist

2023-12-02 19:55 UTC, jay-goettelmann-nyu requested changes
Hey Raymond.  Good start.  Please see my comments for a couple needed changes.  Thansk!

2023-12-02 19:55 UTC, jay-goettelmann-nyu commented on features/wishlists.feature
> +    When I visit the "Admin UI Page"
Hey @raymondlu8547, good start but a couple things to update.  #1 I think we will need to create a wishlist first before we test the delete.  We designed our wishlist API to return a 204 No Content response when deleting a non-existent wishlist_id.  (Which is what happens in this case).  In the $.ajax().done() method we should check the response code and perhaps give a different message for each.  Like "Wishlist with ID [5432] successfully deleted" for a 200 response and maybe "Could not find a wishlist to delete with ID [42]" when the response is 204.

So in your behave test you should:
1. Create a wishlist
2. Read the new ID 
3. Try to delete the newly created ID
4. Assert that the message is the 200 success message
5. Try to delete the same ID a second time
6. Assert that the message is the 204 message

2023-12-02 19:55 UTC, jay-goettelmann-nyu commented on service/static/js/rest_api.js
> +            flash_message("Successfully deleted Wishlist with ID " + wishlist_id)
Here you can add a conditional to check for res.status == 204 to set the ID not found message and you can use the else clause to assume it was a successful deletion.

2023-12-11 06:55 UTC, jay-goettelmann-nyu approved these changes
I added a commit to address a couple things.  I will approve but we should have others review as well.

2023-12-11 08:25 UTC, rahilkadakia approved these changes
Looks good. Merging.

2023-12-11 08:25 UTC, merged