added root return info
CSCI-GA-2820-FA23-003/wishlists pull request #87
Opened 2023-11-15 02:27 UTC by raymondlu8547

Added response to root info
Since nothing is known only info returned is how to see list of wishlists

2023-11-15 15:58 UTC, studentgrad0419 requested changes
The automated test is failing becuase of an unused import (see comment).
remember to "make lint" and "green" locally before pushing, thanks.

2023-11-15 15:58 UTC, studentgrad0419 commented on service/routes.py
> +from flask import jsonify, request, abort, make_response, url_for
The test did not pass because "url_for" is not used

2023-11-15 22:31 UTC, jay-goettelmann-nyu requested changes

2023-11-15 22:31 UTC, jay-goettelmann-nyu commented on service/routes.py
> +    [{'id': 1, 'username': 'Alice'}, {'id': 2, 'username': 'Bob'}]
We should remove this @raymondlu8547.  I assume you were using this to test jsonify?

2023-11-16 04:20 UTC, jay-goettelmann-nyu approved these changes

2023-11-16 04:28 UTC, merged